/** The one definition of the path risk tables; see `pathRiskTables.js`. */
export const SENSITIVE_SEGMENT: RegExp;
export const SENSITIVE_STEM: RegExp;
export const SENSITIVE_CAMEL_STEM: RegExp;
export const CI_PATTERNS: readonly RegExp[];
export const CONTAINER_PATTERNS: readonly RegExp[];
export const IAC_PATTERNS: readonly RegExp[];
export const REPO_CONTROL_PATTERNS: readonly RegExp[];
export const SECRET_MATERIAL_PATTERNS: readonly RegExp[];
export const BUILD_SCRIPT_PATTERNS: readonly RegExp[];
export const MIGRATION_PATTERNS: readonly RegExp[];
export const LOCKFILE_NAMES: ReadonlySet<string>;
export const LOCKFILE_PATTERNS: readonly RegExp[];
export const TOOLCHAIN_PIN_NAMES: ReadonlySet<string>;
export const DEPENDENCY_MANIFESTS: ReadonlySet<string>;
export const DEPENDENCY_MANIFEST_PATTERNS: readonly RegExp[];
export const CI_IAC_PATTERNS: readonly RegExp[];
export const TEST_PATTERNS: readonly RegExp[];
export const DOCUMENTATION_OR_ASSET_EXTENSION: RegExp;
export const DATA_OR_CONFIG_EXTENSION: RegExp;
export const DOTENV_CONFIG_FILE: RegExp;
export const RUN_ARTIFACT_DIRECTORY: RegExp;
export const RUN_ARTIFACT_EXTENSION: RegExp;
