'use strict';

const DEFAULT_MAX_FILE_DIFF_CHARS = 5_000;
const MAX_FILE_DIFF_CHARS_CAP = 2_000_000;

const REVIEW_IGNORE_RULES = [
  { pattern: 'package-lock.json', category: 'lockfile', reason: 'Dependency lockfiles are skipped by default.' },
  { pattern: 'Cargo.lock', category: 'lockfile', reason: 'Dependency lockfiles are skipped by default.' },
  { pattern: 'Gemfile.lock', category: 'lockfile', reason: 'Dependency lockfiles are skipped by default.' },
  { pattern: 'go.sum', category: 'lockfile', reason: 'Dependency lockfiles are skipped by default.' },
  { pattern: 'mix.lock', category: 'lockfile', reason: 'Dependency lockfiles are skipped by default.' },
  { pattern: 'poetry.lock', category: 'lockfile', reason: 'Dependency lockfiles are skipped by default.' },
  { pattern: 'Pipfile.lock', category: 'lockfile', reason: 'Dependency lockfiles are skipped by default.' },
  { pattern: 'composer.lock', category: 'lockfile', reason: 'Dependency lockfiles are skipped by default.' },
  { pattern: 'yarn.lock', category: 'lockfile', reason: 'Dependency lockfiles are skipped by default.' },
  { pattern: 'pnpm-lock.yaml', category: 'lockfile', reason: 'Dependency lockfiles are skipped by default.' },
  { pattern: 'npm-shrinkwrap.json', category: 'lockfile', reason: 'Dependency lockfiles are skipped by default.' },
  { pattern: 'bun.lockb', category: 'lockfile', reason: 'Dependency lockfiles are skipped by default.' },
  { pattern: 'packages.lock.json', category: 'lockfile', reason: 'Dependency lockfiles are skipped by default.' },
  { pattern: '**/__snapshots__/**', category: 'snapshot', reason: 'Test snapshots are skipped by default.' },
  { pattern: '*.snap', category: 'snapshot', reason: 'Test snapshots are skipped by default.' },
  { pattern: '*.generated.ts', category: 'generated', reason: 'Generated files are skipped by default.' },
  { pattern: '*.generated.js', category: 'generated', reason: 'Generated files are skipped by default.' },
  { pattern: '*.generated.tsx', category: 'generated', reason: 'Generated files are skipped by default.' },
  { pattern: '*.generated.jsx', category: 'generated', reason: 'Generated files are skipped by default.' },
  { pattern: '*.generated.json', category: 'generated', reason: 'Generated files are skipped by default.' },
  { pattern: '*.generated.yaml', category: 'generated', reason: 'Generated files are skipped by default.' },
  { pattern: '*.generated.yml', category: 'generated', reason: 'Generated files are skipped by default.' },
  { pattern: '*.pb.go', category: 'generated', reason: 'Generated files are skipped by default.' },
  { pattern: '*.pb.cc', category: 'generated', reason: 'Generated files are skipped by default.' },
  { pattern: '*.pb.h', category: 'generated', reason: 'Generated files are skipped by default.' },
  { pattern: '*_pb2.py', category: 'generated', reason: 'Generated files are skipped by default.' },
  { pattern: '**/dist/**', category: 'build_output', reason: 'Build output is skipped by default.' },
  { pattern: '**/build/**', category: 'build_output', reason: 'Build output is skipped by default.' },
  { pattern: '**/out/**', category: 'build_output', reason: 'Build output is skipped by default.' },
  { pattern: '**/node_modules/**', category: 'dependency_cache', reason: 'Generated dependency caches are skipped by default.' },
  { pattern: '**/.next/**', category: 'dependency_cache', reason: 'Generated dependency caches are skipped by default.' },
  { pattern: '**/.nuxt/**', category: 'dependency_cache', reason: 'Generated dependency caches are skipped by default.' },
  { pattern: '*.min.js', category: 'minified', reason: 'Minified assets are skipped by default.' },
  { pattern: '*.min.css', category: 'minified', reason: 'Minified assets are skipped by default.' },
  { pattern: '*.min.map', category: 'minified', reason: 'Minified assets are skipped by default.' },
  { pattern: '*.map', category: 'source_map', reason: 'Source maps are skipped by default.' },
  { pattern: '*.png', category: 'binary', reason: 'Binary files are skipped by default.' },
  { pattern: '*.jpg', category: 'binary', reason: 'Binary files are skipped by default.' },
  { pattern: '*.jpeg', category: 'binary', reason: 'Binary files are skipped by default.' },
  { pattern: '*.gif', category: 'binary', reason: 'Binary files are skipped by default.' },
  { pattern: '*.ico', category: 'binary', reason: 'Binary files are skipped by default.' },
  { pattern: '*.woff', category: 'binary', reason: 'Binary files are skipped by default.' },
  { pattern: '*.woff2', category: 'binary', reason: 'Binary files are skipped by default.' },
  { pattern: '*.ttf', category: 'binary', reason: 'Binary files are skipped by default.' },
  { pattern: '*.eot', category: 'binary', reason: 'Binary files are skipped by default.' },
  { pattern: '*.pdf', category: 'binary', reason: 'Binary files are skipped by default.' },
  { pattern: '*.zip', category: 'binary', reason: 'Binary files are skipped by default.' },
  { pattern: '*.gz', category: 'binary', reason: 'Binary files are skipped by default.' },
  { pattern: '*.jar', category: 'binary', reason: 'Binary files are skipped by default.' },
  { pattern: '*.dll', category: 'binary', reason: 'Binary files are skipped by default.' },
  { pattern: '*.so', category: 'binary', reason: 'Binary files are skipped by default.' },
  { pattern: '*.dylib', category: 'binary', reason: 'Binary files are skipped by default.' },
];

module.exports = {
  DEFAULT_MAX_FILE_DIFF_CHARS,
  MAX_FILE_DIFF_CHARS_CAP,
  REVIEW_IGNORE_RULES,
};
