# syntax=docker/dockerfile:1.7

ARG GO_BASE_IMAGE=golang:1.24-bookworm@sha256:1a6d4452c65dea36aac2e2d606b01b4a029ec90cc1ae53890540ce6173ea77ac

FROM ${GO_BASE_IMAGE} AS build
WORKDIR /src/k8s-operator
COPY k8s-operator/go.mod k8s-operator/go.sum ./
RUN go mod download
COPY k8s-operator ./
RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 \
    go build -trimpath -ldflags="-s -w" -o /out/manager .

FROM scratch
COPY --from=build /out/manager /manager
COPY --from=build /etc/ssl/certs/ca-certificates.crt /etc/ssl/certs/ca-certificates.crt
USER 1000:1000
ENTRYPOINT ["/manager"]
