import { ParsedPRPayload } from '../github/eventHandler';
import { CtReviewConfigV3 } from '../config/schema';
import { GitHubInstallationClient } from '../github/installationClient';
import { OmniRouteClient } from '../gateway/omniRouteClient';
import { logger } from '../utils/logger';

export interface PersonaContext {
  payload: ParsedPRPayload;
  config: CtReviewConfigV3;
  github: GitHubInstallationClient;
  omniRoute?: OmniRouteClient;
}

export interface FollowupPRResult {
  created: boolean;
  prNumber: number;
  url: string;
  summary?: string;
}

export async function executeDocsPersona(ctx: PersonaContext): Promise<FollowupPRResult> {
  const { payload, github, omniRoute } = ctx;
  const { owner, repo, prNumber, title, targetBranch = 'main' } = payload;

  logger.info(`Executing Docs Persona for ${owner}/${repo} #${prNumber}`);

  let changedFiles = payload.changedFiles || [];
  if (changedFiles.length === 0) {
    try {
      const files = await github.getChangedFiles(owner, repo, prNumber);
      changedFiles = files;
    } catch (err: any) {
      logger.warn(`Could not fetch changed files for #${prNumber}: ${err.message}`);
    }
  }

  let docContent = `# Documentation Updates for PR #${prNumber}\n\n`;
  docContent += `**Original PR Title**: ${title}\n`;
  docContent += `**Target Branch**: ${targetBranch}\n\n`;
  docContent += `## Changed Components\n`;

  if (changedFiles.length > 0) {
    for (const file of changedFiles) {
      docContent += `- \`${file.path}\`\n`;
    }
  } else {
    docContent += `- Repository files modified in PR #${prNumber}\n`;
  }

  if (omniRoute) {
    try {
      const response = await omniRoute.complete({
        model: 'codex/gpt-5.6-sol-high',
        messages: [
          { role: 'system', content: 'You are a technical documentation specialist. Generate clear markdown documentation for the merged pull request.' },
          { role: 'user', content: `Generate documentation updates for PR #${prNumber}: ${title}.\nFiles changed:\n${changedFiles.map((f) => f.path).join('\n')}` },
        ],
        timeoutMs: 15_000,
      });
      docContent += `\n## Detailed API & Architecture Changes\n${response.content}\n`;
    } catch (err: any) {
      logger.warn(`OmniRoute completion unavailable for docs-persona: ${err.message}`);
      docContent += `\n## Overview\nAutomated documentation entry generated for code changes merged in #${prNumber}.\n`;
    }
  } else {
    docContent += `\n## Overview\nAutomated documentation entry generated for code changes merged in #${prNumber}.\n`;
  }

  const baseSha = await github.getBranchRef(owner, repo, targetBranch);
  const newBranch = `ct-review/docs-followup-pr-${prNumber}`;

  try {
    await github.createBranch(owner, repo, newBranch, baseSha);
  } catch (err: any) {
    logger.warn(`Branch ${newBranch} creation warning: ${err.message}`);
  }

  const docFilePath = `docs/updates/pr-${prNumber}-docs.md`;
  await github.createOrUpdateFile({
    owner,
    repo,
    path: docFilePath,
    message: `docs: update documentation for merged PR #${prNumber}`,
    content: docContent,
    branch: newBranch,
  });

  const prTitle = `docs: follow-up documentation for #${prNumber}`;
  const prBody = `Automated documentation update generated by ct-review-bot docs-persona for merged PR #${prNumber}.\n\nOriginal PR: ${title}`;

  const newPr = await github.createPullRequest({
    owner,
    repo,
    title: prTitle,
    body: prBody,
    head: newBranch,
    base: targetBranch,
  });

  try {
    await github.postIssueComment(
      owner,
      repo,
      prNumber,
      `docs-persona created follow-up PR: #${newPr.number} (${newPr.html_url})`
    );
  } catch (err: any) {
    logger.warn(`Failed to post cross-reference comment on original PR #${prNumber}: ${err.message}`);
  }

  return {
    created: true,
    prNumber: newPr.number,
    url: newPr.html_url,
    summary: `Created documentation PR #${newPr.number}`,
  };
}
