import { ParsedPRPayload } from '../github/eventHandler';
import { CtReviewConfigV3 } from '../config/schema';
import { GitHubInstallationClient } from '../github/installationClient';
import { ReviewModelClient } from '../gateway/openRouterClient';
import { logger } from '../utils/logger';

export interface PersonaContext {
  payload: ParsedPRPayload;
  config: CtReviewConfigV3;
  github: GitHubInstallationClient;
  /** @deprecated Unsupported legacy field; ignored. Pass the OpenRouter client via modelClient. */
  omniRoute?: ReviewModelClient;
  modelClient?: ReviewModelClient;
}

export interface FollowupPRResult {
  created: boolean;
  prNumber: number;
  url: string;
  summary?: string;
}

export async function executeMarketingPersona(ctx: PersonaContext): Promise<FollowupPRResult> {
  const { payload, github } = ctx;
  const modelClient = ctx.modelClient;
  const { owner, repo, prNumber, title, targetBranch = 'main' } = payload;

  logger.info(`Executing Marketing Persona for ${owner}/${repo} #${prNumber}`);

  let releaseNotes = `# Release Notes for PR #${prNumber}\n\n`;
  releaseNotes += `**Feature / Update**: ${title}\n\n`;
  releaseNotes += `## Customer Highlights\n`;

  if (modelClient) {
    try {
      const response = await modelClient.complete({
        model: 'openrouter/auto',
        messages: [
          { role: 'system', content: 'You are a product marketing manager. Synthesize clear, engaging release notes for customer-facing feature updates.' },
          { role: 'user', content: `Create release notes for merged PR #${prNumber}: ${title}\nPR Body:\n${payload.body}` },
        ],
        timeoutMs: 15_000,
      });
      releaseNotes += `${response.content}\n`;
    } catch (err: any) {
      logger.warn(`OpenRouter completion unavailable for marketing-persona: ${err.message}`);
      releaseNotes += `- We are excited to announce new updates and enhancements included in PR #${prNumber} (${title}).\n`;
    }
  } else {
    releaseNotes += `- We are excited to announce new updates and enhancements included in PR #${prNumber} (${title}).\n`;
  }

  const baseSha = await github.getBranchRef(owner, repo, targetBranch);
  const newBranch = `ct-review/marketing-followup-pr-${prNumber}`;

  try {
    await github.createBranch(owner, repo, newBranch, baseSha);
  } catch (err: any) {
    logger.warn(`Branch ${newBranch} creation warning: ${err.message}`);
  }

  const filePath = `notes/release-updates-pr-${prNumber}.md`;
  await github.createOrUpdateFile({
    owner,
    repo,
    path: filePath,
    message: `marketing: release notes follow-up for PR #${prNumber}`,
    content: releaseNotes,
    branch: newBranch,
  });

  const prTitle = `marketing: release notes follow-up for #${prNumber}`;
  const prBody = `Automated release notes generated by ct-review-bot marketing-persona for merged PR #${prNumber}.\n\nOriginal PR: ${title}`;

  const newPr = await github.createPullRequest({
    owner,
    repo,
    title: prTitle,
    body: prBody,
    head: newBranch,
    base: targetBranch,
  });

  try {
    await github.postIssueComment(
      owner,
      repo,
      prNumber,
      `marketing-persona created follow-up PR: #${newPr.number} (${newPr.html_url})`
    );
  } catch (err: any) {
    logger.warn(`Failed to post cross-reference comment on original PR #${prNumber}: ${err.message}`);
  }

  return {
    created: true,
    prNumber: newPr.number,
    url: newPr.html_url,
    summary: `Created marketing release notes PR #${newPr.number}`,
  };
}
