/**
 * AUTO-GENERATED FILE - DO NOT MODIFY DIRECTLY.
 * Generated by scripts/generate-omniroute-providers.ts
 */

export type ProviderType =
  | 'openai'
  | 'anthropic'
  | 'gemini'
  | 'grok'
  | 'deepseek'
  | 'glm'
  | 'doppler'
  | 'ollama'
  | 'custom-openai'
  | 'codex'
  | 'agy';

export interface GeneratedProviderMeta {
  id: ProviderType;
  displayName: string;
  defaultBaseUrl: string;
  provenancePrefixes: readonly string[];
  defaultModel: string;
  supportedModels: readonly string[];
  supportsCustomModels: boolean;
  requiresApiKey: boolean;
}

export const OMNIROUTE_GENERATED_PROVIDERS: Record<ProviderType, GeneratedProviderMeta> = {
  "openai": {
    "id": "openai",
    "displayName": "OpenAI",
    "defaultBaseUrl": "https://api.openai.com/v1",
    "provenancePrefixes": [
      "openai",
      "gpt"
    ],
    "defaultModel": "openai/gpt-5.6-luna:high",
    "supportedModels": [
      "openai/gpt-5.6-luna:high",
      "openai/gpt-5.6-luna",
      "openrouter/5.6-luna-high",
      "gpt-5.6-sol",
      "o3-mini",
      "gpt-4o",
      "gpt-4o-mini"
    ],
    "supportsCustomModels": true,
    "requiresApiKey": true
  },
  "anthropic": {
    "id": "anthropic",
    "displayName": "Anthropic Claude",
    "defaultBaseUrl": "https://api.anthropic.com/v1",
    "provenancePrefixes": [
      "claude",
      "anthropic"
    ],
    "defaultModel": "claude-5-haiku:high",
    "supportedModels": [
      "claude-5-haiku:high",
      "claude-5-haiku",
      "claude-3-7-sonnet",
      "claude-5-sonnet",
      "claude-opus-4-8",
      "claude-3-5-sonnet",
      "agy/claude-opus-4-6-thinking"
    ],
    "supportsCustomModels": false,
    "requiresApiKey": true
  },
  "gemini": {
    "id": "gemini",
    "displayName": "Google Gemini",
    "defaultBaseUrl": "https://generativelanguage.googleapis.com/v1beta",
    "provenancePrefixes": [
      "gemini",
      "google"
    ],
    "defaultModel": "google/gemini-3.7-flash:high",
    "supportedModels": [
      "google/gemini-3.7-flash:high",
      "google/gemini-3.7-flash",
      "google/gemini-3.6-flash",
      "google/gemini-2.5-pro"
    ],
    "supportsCustomModels": false,
    "requiresApiKey": true
  },
  "grok": {
    "id": "grok",
    "displayName": "xAI Grok",
    "defaultBaseUrl": "https://api.x.ai/v1",
    "provenancePrefixes": [
      "grok-cli"
    ],
    "defaultModel": "grok-cli/grok-4.5",
    "supportedModels": [
      "grok-cli/grok-4.5",
      "grok-2"
    ],
    "supportsCustomModels": false,
    "requiresApiKey": true
  },
  "deepseek": {
    "id": "deepseek",
    "displayName": "DeepSeek AI",
    "defaultBaseUrl": "https://api.deepseek.com/v1",
    "provenancePrefixes": [
      "deepseek"
    ],
    "defaultModel": "deepseek/deepseek-v4-flash-0731:high",
    "supportedModels": [
      "deepseek/deepseek-v4-flash-0731:high",
      "deepseek/deepseek-v4-flash-0731:low",
      "accounts/fireworks/models/deepseek-v4-flash-0731",
      "deepseek-v4-pro",
      "deepseek-r1",
      "deepseek-v3"
    ],
    "supportsCustomModels": true,
    "requiresApiKey": true
  },
  "glm": {
    "id": "glm",
    "displayName": "GLM / Synthetic Arbiter",
    "defaultBaseUrl": "https://api.omniroute.internal/v1",
    "provenancePrefixes": [
      "glm",
      "synthetic"
    ],
    "defaultModel": "glm-5.3-flash",
    "supportedModels": [
      "glm-5.3-flash",
      "glm-5.2",
      "synthetic/v1",
      "synthetic/glm-5.2-high"
    ],
    "supportsCustomModels": false,
    "requiresApiKey": false
  },
  "doppler": {
    "id": "doppler",
    "displayName": "Doppler Secret Sync",
    "defaultBaseUrl": "https://api.doppler.com/v3",
    "provenancePrefixes": [
      "doppler"
    ],
    "defaultModel": "doppler-sync-v1",
    "supportedModels": [
      "doppler-sync-v1"
    ],
    "supportsCustomModels": false,
    "requiresApiKey": true
  },
  "ollama": {
    "id": "ollama",
    "displayName": "Ollama Local LLM",
    "defaultBaseUrl": "http://localhost:11434/v1",
    "provenancePrefixes": [
      "ollama",
      "local"
    ],
    "defaultModel": "llama3.3",
    "supportedModels": [
      "llama3.3",
      "qwen2.5-coder",
      "deepseek-r1:8b"
    ],
    "supportsCustomModels": true,
    "requiresApiKey": false
  },
  "custom-openai": {
    "id": "custom-openai",
    "displayName": "Custom OpenAI-Compatible",
    "defaultBaseUrl": "https://api.custom-llm.com/v1",
    "provenancePrefixes": [
      "custom"
    ],
    "defaultModel": "custom-model-v1",
    "supportedModels": [
      "custom-model-v1"
    ],
    "supportsCustomModels": true,
    "requiresApiKey": true
  },
  "codex": {
    "id": "codex",
    "displayName": "Codex Gateway",
    "defaultBaseUrl": "https://api.codex.internal/v1",
    "provenancePrefixes": [
      "codex",
      "cx"
    ],
    "defaultModel": "codex/gpt-5.6-sol-high",
    "supportedModels": [
      "codex/gpt-5.6-sol-high",
      "gpt-5.6-sol"
    ],
    "supportsCustomModels": false,
    "requiresApiKey": true
  },
  "agy": {
    "id": "agy",
    "displayName": "AGY Thinking Engine",
    "defaultBaseUrl": "https://api.agy.internal/v1",
    "provenancePrefixes": [
      "agy"
    ],
    "defaultModel": "agy/claude-opus-4-6-thinking",
    "supportedModels": [
      "agy/claude-opus-4-6-thinking"
    ],
    "supportsCustomModels": false,
    "requiresApiKey": true
  }
};

export const OMNIROUTE_GENERATED_MODEL_LIST: readonly string[] = [
  "openai/gpt-5.6-luna:high",
  "openai/gpt-5.6-luna",
  "openrouter/5.6-luna-high",
  "gpt-5.6-sol",
  "o3-mini",
  "gpt-4o",
  "gpt-4o-mini",
  "claude-5-haiku:high",
  "claude-5-haiku",
  "claude-3-7-sonnet",
  "claude-5-sonnet",
  "claude-opus-4-8",
  "claude-3-5-sonnet",
  "agy/claude-opus-4-6-thinking",
  "google/gemini-3.7-flash:high",
  "google/gemini-3.7-flash",
  "google/gemini-3.6-flash",
  "google/gemini-2.5-pro",
  "grok-cli/grok-4.5",
  "grok-2",
  "deepseek/deepseek-v4-flash-0731:high",
  "deepseek/deepseek-v4-flash-0731:low",
  "accounts/fireworks/models/deepseek-v4-flash-0731",
  "deepseek-v4-pro",
  "deepseek-r1",
  "deepseek-v3",
  "glm-5.3-flash",
  "glm-5.2",
  "synthetic/v1",
  "synthetic/glm-5.2-high",
  "doppler-sync-v1",
  "llama3.3",
  "qwen2.5-coder",
  "deepseek-r1:8b",
  "custom-model-v1",
  "codex/gpt-5.6-sol-high",
  "openrouter/auto",
  "deepseek/deepseek-v4.1-flash",
  "deepseek/deepseek-v4.1-flash:high",
  "deepseek/deepseek-v4.1-flash:low",
  "deepseek-v4.1-flash",
  "openrouter/deepseek/deepseek-v4.1-flash",
  "z-ai/glm-5.3-flash",
  "synthetic/glm-5.3-flash",
  "synthetic/hf:zai-org/GLM-5.3-Flash",
  "hf:zai-org/GLM-5.3-Flash",
  "ollama/glm-5.3-flash",
  "bifrost/pr-reviewer",
  "openrouter/anthropic/claude-3.7-sonnet",
  "openrouter/deepseek/deepseek-r1",
  "openrouter/google/gemini-2.5-pro",
  "openrouter/qwen/qwen-2.5-72b-instruct",
  "openrouter/openai/gpt-4o",
  "openrouter/openai/gpt-4o-mini",
  "openrouter/anthropic/claude-3.5-sonnet",
  "openrouter/deepseek/deepseek-v3",
  "openrouter/google/gemini-1.5-pro",
  "openrouter/anthropic/claude-haiku-4.5",
  "openrouter/anthropic/claude-opus-4.8",
  "openrouter/openai/gpt-5.6-luna",
  "openrouter/openai/gpt-5.6-luna:high",
  "openrouter/anthropic/claude-5-haiku:high",
  "openrouter/anthropic/claude-5-haiku",
  "anthropic/claude-5-haiku:high",
  "anthropic/claude-5-haiku",
  "openai/gpt-4o",
  "openai/gpt-4o-mini",
  "gemini-1.5-pro",
  "google/gemini-1.5-pro",
  "google/gemini-2.5-flash",
  "openrouter/google/gemini-3.7-flash",
  "openrouter/google/gemini-2.5-flash",
  "deepseek/deepseek-v4-flash-0731",
  "openrouter/deepseek/deepseek-v4-flash-0731:low",
  "openrouter/deepseek/deepseek-v4-flash-0731:high",
  "qwen/qwen-3.8-27b:high",
  "qwen/qwen-3.8-27b",
  "qwen/qwen-2.5-72b-instruct",
  "openrouter/qwen/qwen-3.8-27b:high",
  "anthropic/claude-3.7-sonnet",
  "anthropic/claude-opus-4.8",
  "synthetic/hf:moonshotai/Kimi-K3",
  "synthetic/hf:zai-org/GLM-5.2",
  "synthetic/hf:zai-org/GLM-4.7-Flash",
  "synthetic/hf:Qwen/Qwen3.6-27B",
  "claude-haiku-4.5",
  "claude-haiku",
  "codex-gateway/gpt-5.6-sol-high",
  "claude/claude-opus-4-8",
  "opencode-go/glm-5.2",
  "opencode-go/glm-5.3-flash",
  "claude/claude-haiku-4-5"
];
