//go:build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha2

import (
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DispatchTimingStatus) DeepCopyInto(out *DispatchTimingStatus) {
	*out = *in
	if in.ReceivedAt != nil {
		in, out := &in.ReceivedAt, &out.ReceivedAt
		*out = (*in).DeepCopy()
	}
	if in.JobCreatedAt != nil {
		in, out := &in.JobCreatedAt, &out.JobCreatedAt
		*out = (*in).DeepCopy()
	}
	if in.PodScheduledAt != nil {
		in, out := &in.PodScheduledAt, &out.PodScheduledAt
		*out = (*in).DeepCopy()
	}
	if in.ImageObservedAt != nil {
		in, out := &in.ImageObservedAt, &out.ImageObservedAt
		*out = (*in).DeepCopy()
	}
	if in.ProcessStartedAt != nil {
		in, out := &in.ProcessStartedAt, &out.ProcessStartedAt
		*out = (*in).DeepCopy()
	}
	if in.CompletedAt != nil {
		in, out := &in.CompletedAt, &out.CompletedAt
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DispatchTimingStatus.
func (in *DispatchTimingStatus) DeepCopy() *DispatchTimingStatus {
	if in == nil {
		return nil
	}
	out := new(DispatchTimingStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PRReviewJob) DeepCopyInto(out *PRReviewJob) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PRReviewJob.
func (in *PRReviewJob) DeepCopy() *PRReviewJob {
	if in == nil {
		return nil
	}
	out := new(PRReviewJob)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PRReviewJob) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PRReviewJobList) DeepCopyInto(out *PRReviewJobList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]PRReviewJob, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PRReviewJobList.
func (in *PRReviewJobList) DeepCopy() *PRReviewJobList {
	if in == nil {
		return nil
	}
	out := new(PRReviewJobList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PRReviewJobList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PRReviewJobSpec) DeepCopyInto(out *PRReviewJobSpec) {
	*out = *in
	if in.ExecutionAttempt != nil {
		in, out := &in.ExecutionAttempt, &out.ExecutionAttempt
		*out = new(int32)
		**out = **in
	}
	in.ReceivedAt.DeepCopyInto(&out.ReceivedAt)
	in.TerminalDeadline.DeepCopyInto(&out.TerminalDeadline)
	if in.PreparedReview != nil {
		in, out := &in.PreparedReview, &out.PreparedReview
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PRReviewJobSpec.
func (in *PRReviewJobSpec) DeepCopy() *PRReviewJobSpec {
	if in == nil {
		return nil
	}
	out := new(PRReviewJobSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PRReviewJobStatus) DeepCopyInto(out *PRReviewJobStatus) {
	*out = *in
	if in.StartTime != nil {
		in, out := &in.StartTime, &out.StartTime
		*out = (*in).DeepCopy()
	}
	if in.CompletionTime != nil {
		in, out := &in.CompletionTime, &out.CompletionTime
		*out = (*in).DeepCopy()
	}
	if in.Timing != nil {
		in, out := &in.Timing, &out.Timing
		*out = new(DispatchTimingStatus)
		(*in).DeepCopyInto(*out)
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PRReviewJobStatus.
func (in *PRReviewJobStatus) DeepCopy() *PRReviewJobStatus {
	if in == nil {
		return nil
	}
	out := new(PRReviewJobStatus)
	in.DeepCopyInto(out)
	return out
}
