// Code generated by deepcopy-gen. DO NOT EDIT.

package v1alpha2

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime"
)

func (in *PRReviewJob) DeepCopyInto(out *PRReviewJob) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
}

func (in *PRReviewJob) DeepCopy() *PRReviewJob {
	if in == nil {
		return nil
	}
	out := new(PRReviewJob)
	in.DeepCopyInto(out)
	return out
}

func (in *PRReviewJob) DeepCopyObject() runtime.Object {
	if copy := in.DeepCopy(); copy != nil {
		return copy
	}
	return nil
}

func (in *PRReviewJobList) DeepCopyInto(out *PRReviewJobList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		out.Items = make([]PRReviewJob, len(in.Items))
		for i := range in.Items {
			in.Items[i].DeepCopyInto(&out.Items[i])
		}
	}
}

func (in *PRReviewJobList) DeepCopy() *PRReviewJobList {
	if in == nil {
		return nil
	}
	out := new(PRReviewJobList)
	in.DeepCopyInto(out)
	return out
}

func (in *PRReviewJobList) DeepCopyObject() runtime.Object {
	if copy := in.DeepCopy(); copy != nil {
		return copy
	}
	return nil
}

func (in *PRReviewJobSpec) DeepCopyInto(out *PRReviewJobSpec) {
	*out = *in
}

func (in *PRReviewJobSpec) DeepCopy() *PRReviewJobSpec {
	if in == nil {
		return nil
	}
	out := new(PRReviewJobSpec)
	in.DeepCopyInto(out)
	return out
}

func (in *PRReviewJobStatus) DeepCopyInto(out *PRReviewJobStatus) {
	*out = *in
	if in.StartTime != nil {
		out.StartTime = in.StartTime.DeepCopy()
	}
	if in.CompletionTime != nil {
		out.CompletionTime = in.CompletionTime.DeepCopy()
	}
	if in.Timing != nil {
		out.Timing = new(DispatchTimingStatus)
		if in.Timing.ReceivedAt != nil {
			out.Timing.ReceivedAt = in.Timing.ReceivedAt.DeepCopy()
		}
		if in.Timing.JobCreatedAt != nil {
			out.Timing.JobCreatedAt = in.Timing.JobCreatedAt.DeepCopy()
		}
		if in.Timing.PodScheduledAt != nil {
			out.Timing.PodScheduledAt = in.Timing.PodScheduledAt.DeepCopy()
		}
		if in.Timing.ImageObservedAt != nil {
			out.Timing.ImageObservedAt = in.Timing.ImageObservedAt.DeepCopy()
		}
		if in.Timing.ProcessStartedAt != nil {
			out.Timing.ProcessStartedAt = in.Timing.ProcessStartedAt.DeepCopy()
		}
		if in.Timing.CompletedAt != nil {
			out.Timing.CompletedAt = in.Timing.CompletedAt.DeepCopy()
		}
	}
	if in.Conditions != nil {
		out.Conditions = make([]metav1.Condition, len(in.Conditions))
		for i := range in.Conditions {
			in.Conditions[i].DeepCopyInto(&out.Conditions[i])
		}
	}
}

func (in *PRReviewJobStatus) DeepCopy() *PRReviewJobStatus {
	if in == nil {
		return nil
	}
	out := new(PRReviewJobStatus)
	in.DeepCopyInto(out)
	return out
}
