import yaml from 'js-yaml';
import { CtReviewConfigV3, ctReviewConfigV3Schema, V3_PROVIDER_MODELS } from '../config/schema';
import { StackScanResult } from './stackScanner';

export interface ConfigGenerationOptions {
  scanResult?: StackScanResult;
  profile?: 'chill' | 'balanced' | 'assertive';
  ticketEnforcement?: boolean;
  selectedPersonaIds?: string[];
  customPathFilters?: string[];
}

export function generateCtReviewConfig(options: ConfigGenerationOptions): { yamlText: string; config: CtReviewConfigV3 } {
  const profile = options.profile || options.scanResult?.recommendedProfile || 'balanced';
  const ticketEnforcement = options.ticketEnforcement ?? false;
  const pathFilters = options.customPathFilters || options.scanResult?.recommendedPathFilters || [
    'node_modules/**',
    'dist/**',
    'build/**',
    'target/**',
    'vendor/**',
    'coverage/**',
    'package-lock.json',
    'yarn.lock',
  ];

  const availablePersonas = options.scanResult?.recommendedPersonas || [
    {
      id: 'shield',
      name: 'Security Shield',
      charter: 'builtin:security',
      paths: ['**'],
      required: true,
      providers: ['synthetic', 'codex'] as any,
    },
    {
      id: 'architect',
      name: 'System Architect',
      charter: 'builtin:correctness',
      paths: ['**/*.ts', '**/*.js'],
      required: true,
      providers: ['synthetic', 'codex'] as any,
    },
  ];

  const selectedPersonas = availablePersonas.filter(
    (p) => !options.selectedPersonaIds || options.selectedPersonaIds.includes(p.id) || p.required
  );

  const personas = selectedPersonas.map((p) => ({
    id: p.id,
    enabled: true,
    required: p.required,
    charter: p.charter,
    paths: p.paths,
    providers: p.providers,
  }));

  const usedProviders = new Set<string>();
  personas.forEach((p) => p.providers.forEach((prov: string) => usedProviders.add(prov)));
  usedProviders.add('synthetic');
  usedProviders.add('codex');

  const providerList = Array.from(usedProviders).map((id) => ({
    id: id as any,
    enabled: true,
    model: (V3_PROVIDER_MODELS as any)[id] || 'synthetic',
    effort: 'low' as const,
    review_timeout_s: 60,
    arbiter_timeout_s: 45,
  }));

  const configObj: CtReviewConfigV3 = {
    version: 3,
    profile,
    quorum: Math.min(2, providerList.length),
    personas,
    reviews: {
      profile,
      reviewer_effort: 'low',
      default_max_turns: 20,
      confidence_threshold: 70,
      mascot: true,
      ticket_enforcement: ticketEnforcement,
      request_changes_workflow: true,
      high_level_summary: true,
      poem: false,
      review_status: true,
      collapse_walkthrough: false,
      sequence_diagrams: true,
      path_instructions: [],
    },
    chat: {
      auto_reply: true,
      max_context_turns: 10,
      art_mascot_response: true,
    },
    knowledge_base: {
      learnings: true,
      issues: true,
      pull_requests: true,
      custom_instructions: [],
    },
    path_filters: pathFilters,
    auto_review: {
      enabled: true,
      ignore_drafts: true,
      review_drafts: false,
      triggers: ['pr_opened', 'pr_synchronize', '@ct-review'],
      labels: [],
      ignore_patterns: [],
      drafts: false,
    },
    dials: {
      memory_engine: true,
      mascot: true,
      confidence_threshold: 70,
      ticket_enforcement: ticketEnforcement,
    },
    mcps: [],
    on_pr_close: {
      create_followup_prs: [],
      sync_productlane: false,
    },
    reviewers: {
      execution: 'personas',
      fallback: 'ordered',
      overall_timeout_s: 180,
      providers: providerList,
      arbiter: {
        order: providerList.map((p) => p.id),
      },
    },
    path_instructions: [],
    rules: [
      {
        id: 'no-hardcoded-secrets',
        rule: 'Never allow hardcoded API keys, tokens, or private credentials in code.',
        scope: ['**'],
        severity: 'P0',
      },
    ],
  };

  const parsed = ctReviewConfigV3Schema.parse(configObj);
  const yamlText = `# Auto-generated by CT-Review-Bot Onboarding Wizard\n# Generated: ${new Date().toISOString()}\n\n` + yaml.dump(parsed, { indent: 2 });

  return { yamlText, config: parsed };
}

export function generateReviewConfig(stackInfo: any): string {
  const result = generateCtReviewConfig({
    profile: 'balanced',
  });
  return result.yamlText;
}
