import test from 'node:test';
import assert from 'node:assert/strict';
import { execFileSync } from 'node:child_process';
import { mkdtempSync, readFileSync, rmSync, writeFileSync } from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

import {
  buildLocalConfig,
  buildLocalEnvironment,
  buildReviewInvocation,
  loadLocalPolicy,
  validateReviewSource,
} from './review-yeti-local.mjs';

const repoRoot = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const policy = loadLocalPolicy();
const bifrostTransport = policy.review_yeti.transports.find((t) => t.name === 'bifrost');

test('materializes the committed provider order and routing into the local CLI contract (Bifrost primary, OpenRouter fallback)', () => {
  const config = buildLocalConfig(policy);
  const transports = config.github_action.transports;

  assert.deepEqual(transports.map((transport) => transport.name), ['bifrost', 'openrouter-primary']);
  assert.equal(config.github_action.openrouter.stream, true);
  // Derive from policy; a pinned literal turns any budget change into a spurious failure (#74).
  assert.equal(config.github_action.openrouter.timeout_ms, bifrostTransport.timeout_ms);
  assert.equal(config.github_action.openrouter.ttft_ms, Number(policy.review_yeti.openrouter_ttft_ms));
  assert.equal(config.github_action.openrouter.model, 'ollama/glm-5.3-flash');
  assert.deepEqual(config.github_action.openrouter.models, undefined);
  // Must track policy/review-yeti.json rather than restating a provider preference.
  assert.equal(
    config.github_action.openrouter.provider_routing.sort,
    undefined,
    'bifrost carries no OpenRouter provider_routing',
  );
  assert.equal(config.limits.max_diff_bytes, 2_000_000);
  assert.deepEqual(config.exclude, ['docs/api/autogenerated/**', 'priv/repo/structure.sql', 'apm.lock.yaml', '.apm/**', 'mix.lock', 'package-lock.json', 'Cargo.lock', 'poetry.lock', 'composer.lock', 'yarn.lock', 'pnpm-lock.yaml']);
});

test('passes bounded limits and routing without exposing credential values', () => {
  const env = buildLocalEnvironment(policy, '/tmp/review-yeti-config-test', {
    FIREWORKS_PR_REVIEW_API_KEY: 'fireworks-secret',
    GITHUB_ACTIONS: 'true',
    GITHUB_OUTPUT: '/tmp/should-not-be-used',
    MCP_CONFIG_JSON: '{"servers":[{"id":"ambient-unvalidated"}]}',
  });

  assert.equal(env.GITHUB_ACTIONS, 'false');
  assert.equal(env.GITHUB_OUTPUT, '');
  assert.equal(env.MCP_CONFIG_JSON, undefined);
  assert.equal(env.REVIEW_YETI_CONFIG_DIR, '/tmp/review-yeti-config-test');
  assert.equal(env.FIREWORKS_PR_REVIEW_API_KEY, undefined);
  assert.equal(env.MAX_PERSONAS, String(policy.review_yeti.personas.split(',').length));
  assert.equal(env.MAX_DIFF_CHARS, '2000000');
  assert.equal(env.MAX_FILE_DIFF_CHARS, '524288');
  // Track policy rather than pinning a literal: this assertion went stale the moment
  // lane_deadline_ms changed, turning a routine policy edit into a red main.
  assert.equal(env.LANE_DEADLINE_MS, String(policy.review_yeti.budget.lane_deadline_ms));
  assert.equal(env.LANE_CALL_BUDGET, '24');
  assert.equal(env.OPENROUTER_STREAM, 'true');
  assert.equal(env.OPENROUTER_TIMEOUT_MS, String(bifrostTransport.timeout_ms));
  // Track policy rather than pinning a literal (see LANE_DEADLINE_MS above and #74): REL-499
  // raised openrouter_ttft_ms 60000->75000 after example-api PR #4764 showed persona lanes time
  // out on openrouter-primary; a hardcoded value here would go stale on the next tuning pass.
  // Tracks the global openrouter_ttft_ms alias rather than a per-transport literal.
  assert.equal(env.OPENROUTER_TTFT_MS, String(policy.review_yeti.openrouter_ttft_ms));
  assert.equal(env.OPENROUTER_MAX_ATTEMPTS, '2');
  const transports = JSON.parse(env.REVIEW_YETI_TRANSPORTS);
  assert.deepEqual(transports.map((transport) => transport.name), ['bifrost', 'openrouter-primary']);
  assert.equal(transports[0].model, 'ollama/glm-5.3-flash');
  assert.equal(transports[1].model, 'z-ai/glm-5.3-flash');
});

test('accepts only immutable SHA pairs, diff files, or GitHub pull requests', () => {
  const base = 'a'.repeat(40);
  const head = 'b'.repeat(40);

  assert.equal(validateReviewSource({ base, head }).head, head);
  assert.equal(validateReviewSource({ 'diff-file': './change.diff' })['diff-file'], './change.diff');
  assert.equal(validateReviewSource({ pr: 'exampleorg/example-review-actions#65' }).pr, 'exampleorg/example-review-actions#65');
  assert.equal(validateReviewSource({ pr: 'https://github.com/exampleorg/example-review-actions/pull/65' }).pr.includes('/pull/'), true);
  assert.throws(() => validateReviewSource({ base: 'main', head }), /full commit SHAs/);
  assert.throws(() => validateReviewSource({ base, head: base }), /must differ/);
  assert.throws(() => validateReviewSource({ pr: 'exampleorg/example-review-actions' }), /owner\/repository#number/);
  assert.throws(() => validateReviewSource({ base, head, 'diff-file': './change.diff' }), /exactly one source/);
});

test('builds the delegated invocation without changing source identity', () => {
  assert.deepEqual(
    buildReviewInvocation({
      base: 'a'.repeat(40),
      head: 'b'.repeat(40),
      output: 'review.json',
      model: 'deepseek/deepseek-v4-flash-0731',
      json: true,
    }),
    ['review', '--base', 'a'.repeat(40), '--head', 'b'.repeat(40), '--output', 'review.json', '--model', 'deepseek/deepseek-v4-flash-0731', '--json'],
  );
});

test('delegates to an installed CLI with a temporary 0600 config and cleans it up', () => {
  const tempRoot = mkdtempSync(path.join(os.tmpdir(), 'ct-review-yeti-local-test-'));
  const fakeCli = path.join(tempRoot, 'fake-reviewyeti');
  const receipt = path.join(tempRoot, 'delegation.json');
  const mcpConfigPath = path.join(tempRoot, 'mcp.json');
  writeFileSync(mcpConfigPath, JSON.stringify({
    servers: [{
      id: 'context7-local',
      name: 'Context7 local proxy',
      transport: 'http',
      url: 'http://127.0.0.1:4318/mcp',
      env: { CONTEXT7_API_KEY: 'secret-not-for-logs' },
    }],
  }));
  writeFileSync(fakeCli, `#!/usr/bin/env node
const fs = require('node:fs');
const path = require('node:path');
const configPath = path.join(process.env.REVIEW_YETI_CONFIG_DIR, '.review-yeti.yaml');
const config = JSON.parse(fs.readFileSync(configPath, 'utf8'));
const mcp = JSON.parse(process.env.MCP_CONFIG_JSON);
fs.writeFileSync(process.env.CT_REVIEW_YETI_TEST_RECEIPT, JSON.stringify({
  args: process.argv.slice(2),
  configMode: fs.statSync(configPath).mode & 0o777,
  transportNames: config.github_action.transports.map((transport) => transport.name),
  mcpServerIds: mcp.servers.map((server) => server.id),
  mcpSecretPresent: mcp.servers[0].env.CONTEXT7_API_KEY === 'secret-not-for-logs',
  publicationFlag: process.env.GITHUB_ACTIONS,
}));
process.stdout.write(JSON.stringify({ delegated: true }) + '\\n');
`, { mode: 0o700 });

  try {
    const output = execFileSync(
      path.join(repoRoot, 'scripts/review-yeti-local'),
      ['review', '--base', 'a'.repeat(40), '--head', 'b'.repeat(40), '--json', '--cli-bin', fakeCli, '--mcp-config', mcpConfigPath],
      {
        cwd: repoRoot,
        env: { ...process.env, CT_REVIEW_YETI_TEST_RECEIPT: receipt },
        encoding: 'utf8',
      },
    );
    const delegated = JSON.parse(readFileSync(receipt, 'utf8'));
    assert.equal(JSON.parse(output).delegated, true);
    assert.deepEqual(delegated.args, ['review', '--base', 'a'.repeat(40), '--head', 'b'.repeat(40), '--json']);
    assert.equal(delegated.configMode, 0o600);
    assert.deepEqual(delegated.transportNames, ['bifrost', 'openrouter-primary']);
    assert.deepEqual(delegated.mcpServerIds, ['context7-local']);
    assert.equal(delegated.mcpSecretPresent, true);
    assert.equal(delegated.publicationFlag, 'false');

    const configDir = process.env.REVIEW_YETI_CONFIG_DIR;
    assert.equal(configDir, undefined, 'launcher must not leak its temporary config into the parent process');
  } finally {
    rmSync(tempRoot, { recursive: true, force: true });
  }
});
