import { describe, expect, it } from 'vitest';
import path from 'path';

const modulePath = path.resolve(__dirname, '../../scripts/reorder-diff-sections.mjs');

function section(filePath: string, body = 'content') {
  return [
    `diff --git a/${filePath} b/${filePath}`,
    'index 000000..111111 100644',
    `--- a/${filePath}`,
    `+++ b/${filePath}`,
    '@@ -1 +1 @@',
    `-old ${body}`,
    `+new ${body}`,
    '',
  ].join('\n');
}

describe('reorderDiffSections', () => {
  it('moves generated/lock/vendor/snapshot files to the tail, preserving relative order within tiers', async () => {
    const { reorderDiffSections } = await import(modulePath);
    const diffText = [
      section('package-lock.json'),
      section('src/api/handler.ts'),
      section('src/api/handler_test.ts'),
      section('vendor/thirdparty/lib.js'),
      section('src/lib/util.ts'),
    ].join('');

    const result = reorderDiffSections(diffText);
    expect(result.order).toEqual([
      'src/api/handler.ts',
      'src/lib/util.ts',
      'src/api/handler_test.ts',
      'package-lock.json',
      'vendor/thirdparty/lib.js',
    ]);
    expect(result.ignoredCount).toBe(2);
    expect(result.testCount).toBe(1);
  });

  it('recognizes common test path shapes', async () => {
    const { isTestPath } = await import(modulePath);
    expect(isTestPath('tests/unit/foo.test.ts')).toBe(true);
    expect(isTestPath('src/foo.spec.ts')).toBe(true);
    expect(isTestPath('src/foo_test.exs')).toBe(true);
    expect(isTestPath('__tests__/foo.js')).toBe(true);
    expect(isTestPath('src/foo.ts')).toBe(false);
  });

  it('recognizes the default ignore globs', async () => {
    const { isIgnoredPath } = await import(modulePath);
    expect(isIgnoredPath('yarn.lock')).toBe(true);
    expect(isIgnoredPath('apm.lock.yaml')).toBe(true);
    expect(isIgnoredPath('.apm/manifest.json')).toBe(true);
    expect(isIgnoredPath('docs/api/autogenerated/index.md')).toBe(true);
    expect(isIgnoredPath('priv/repo/structure.sql')).toBe(true);
    expect(isIgnoredPath('src/pipeline/diffCompactor.ts')).toBe(false);
  });

  it('preserves every section exactly once -- reordering never drops content', async () => {
    const { reorderDiffSections } = await import(modulePath);
    const files = ['a.ts', 'b.lock', 'c_test.ts', 'd/vendor/e.js', 'f.ts'];
    const diffText = files.map((f) => section(f, f)).join('');

    const result = reorderDiffSections(diffText);
    expect(result.order.sort()).toEqual([...files].sort());
    for (const f of files) {
      expect(result.text).toContain(`old ${f}`);
      expect(result.text).toContain(`new ${f}`);
    }
    // No accidental duplication.
    expect(result.text.split('diff --git').length - 1).toBe(files.length);
  });

  it('passes through a diff with no matched sections unchanged', async () => {
    const { reorderDiffSections } = await import(modulePath);
    const result = reorderDiffSections('');
    expect(result.text).toBe('');
    expect(result.order).toEqual([]);
  });

  it('handles a single-file diff', async () => {
    const { reorderDiffSections } = await import(modulePath);
    const diffText = section('only.ts');
    const result = reorderDiffSections(diffText);
    expect(result.order).toEqual(['only.ts']);
    expect(result.text).toBe(diffText);
  });
});
