/*
Copyright 2026 CallTelemetry.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// REL-896: the run-Secret naming contract is defined canonically in
// TypeScript (buildRunSecretName, src/k8s/reviewJobProjection.ts) and
// re-implemented here as a regex (job.IsValidRunSecretName / secretNamePattern)
// that gates the v1alpha2 operator's Secret-delete finalizer. This test loads
// the same golden fixture the TypeScript side asserts against
// (tests/unit/reviewJobProjectionSecretNameContract.test.ts) so that a change
// to the naming scheme on either side that is not mirrored on the other fails
// here immediately, instead of leaking a run Secret silently in production.
package job_test

import (
	"encoding/json"
	"os"
	"path/filepath"
	"testing"

	"github.com/calltelemetry/ct-review-bot/k8s-operator/pkg/job"
)

type runSecretNameFixtureEntry struct {
	RunID            string `json:"runId"`
	ExecutionAttempt int32  `json:"executionAttempt"`
	Name             string `json:"name"`
}

type runSecretNameFixture struct {
	Valid   []runSecretNameFixtureEntry `json:"valid"`
	Invalid []string                    `json:"invalid"`
}

func loadRunSecretNameFixture(t *testing.T) runSecretNameFixture {
	t.Helper()
	raw, err := os.ReadFile(filepath.Join("testdata", "run_secret_names.json"))
	if err != nil {
		t.Fatalf("read run_secret_names.json fixture: %v", err)
	}
	var fixture runSecretNameFixture
	if err := json.Unmarshal(raw, &fixture); err != nil {
		t.Fatalf("parse run_secret_names.json fixture: %v", err)
	}
	if len(fixture.Valid) == 0 || len(fixture.Invalid) == 0 {
		t.Fatal("run_secret_names.json fixture must declare at least one valid and one invalid entry")
	}
	return fixture
}

func TestIsValidRunSecretNameAcceptsGoldenFixtureValidNames(t *testing.T) {
	fixture := loadRunSecretNameFixture(t)
	for _, entry := range fixture.Valid {
		t.Run(entry.Name, func(t *testing.T) {
			if !job.IsValidRunSecretName(entry.Name) {
				t.Fatalf("IsValidRunSecretName(%q) = false, want true (generated by the TS buildRunSecretName writer for runId=%q attempt=%d)",
					entry.Name, entry.RunID, entry.ExecutionAttempt)
			}
		})
	}
}

func TestIsValidRunSecretNameRejectsGoldenFixtureInvalidNames(t *testing.T) {
	fixture := loadRunSecretNameFixture(t)
	for _, name := range fixture.Invalid {
		t.Run(name, func(t *testing.T) {
			if job.IsValidRunSecretName(name) {
				t.Fatalf("IsValidRunSecretName(%q) = true, want false: this name is in the golden fixture's deliberately non-conforming set", name)
			}
		})
	}
}
